### ISSUE TITLE
Request: improve compatibility with Minimal UI module

### ISSUE THREAD

**Issue by Merudo** [mawburn/foundry-user-latency#1]
When combined with the [Minimal UI module](https://github.com/saif-ellafi/foundryvtt-minimal-ui) and the player list is set to auto-hide, Ping Logger does not display the ping on the same line as the player colored dot:

![image](https://user-images.githubusercontent.com/7371085/128337504-65c4622d-4bb1-4745-9dcb-63609b059cf1.png)

As you see each player takes two lines in the player list, one for the colored dot and one for their ping.

Ideally, both should be displayed on the same line. Alternatively, the ping could be hidden when in auto-hide mode.

Also see https://github.com/saif-ellafi/foundryvtt-minimal-ui/issues/43

**Comment by mawburn** [comment]
Ah thanks. I'll take a look at it.

**Comment by mawburn** [comment]
@Merudo my first thought is that this is Minimal UI doing it with flexbox or something similar. If that's the case the best bet would be to probably apply a class to the ping that will make that plugin hide it along with the name.

**Comment by mawburn** [comment]
Fixed by https://github.com/saif-ellafi/foundryvtt-minimal-ui/pull/53
