### ISSUE TITLE
update/upgrade not working

### ISSUE THREAD

**Issue by frederik-b** [mawburn/foundry-user-latency#12]
when trying to update the module on a foundry v10 installation it gives the following error:

> The requested manifest at "https://raw.githubusercontent.com/mawburn/foundry-user-latency/main/src/module.json" did not provide module manifest data.

**Comment by thejoester** [comment]
I am getting the same error. Uninstalling and re-installing does not fix. Might just be that it is not being updated for V10 anymore. The module seems to still work.

**Comment by mawburn** [comment]
Duplicate #11
