### ISSUE TITLE
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE for index.css.map

### ISSUE THREAD

**Issue by krobibero** [mawburn/foundry-user-latency#13]
DevTools failed to load source map: Could not load content for https://[XXXXXXXXX]:30000/modules/user-latency/index.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Just uninstalled and reinstalled, same error.  I notice there is no index.css.map file in the module folder

**Comment by mawburn** [comment]
Duplicate #11
