### ISSUE TITLE
A couple of requests

### ISSUE THREAD

**Issue by Geodragon9** [mawburn/foundry-user-latency#14]
Request 1:
In a previous version, the dot was a nice small circle.  The current version shows a large oval on it's side, taking up half the length of the name area.   
Request 2:
An option to hide from players, and only the GM sees the latency.

**Comment by mawburn** [comment]
Yeah, I can take a look at option 1. I haven't checked updates in a while.

I'm not sure how option 2 would work off hand. Everything in Foundry is controlled via the individual clients.

**Comment by mawburn** [comment]
Please redirect this request here: https://github.com/foundryvtt/foundryvtt/issues/11132
