### ISSUE TITLE
Invalid language definition in Package ping-logger:

### ISSUE THREAD

**Issue by jocolamarco** [mawburn/foundry-user-latency#3]
Server log:

[error] Invalid language definition in Package ping-logger: Language JSON path lang/en.json does not exist
[error] Invalid language definition in Package ping-logger: Language JSON path lang/es.json does not exist

FVTT: 0.8.9
DND5e: 1,4,2

**Comment by mawburn** [comment]
Thanks @jocolamarco fixed in v1.2.10
