### ISSUE TITLE
Ping in the camera windows

### ISSUE THREAD

**Issue by CaosFR** [mawburn/foundry-user-latency#4]
Hi, 

Most of the time I hide the player list for have a clean UI. Do you think there is a way to show the ping on the camera box ?

Thanks

**Comment by mawburn** [comment]
@CaosFR Apologies, I missed this. What camera module are you using?

**Comment by CaosFR** [comment]
Dont worry for the delay. I use the Jitsy module : https://github.com/luvolondon/fvtt-module-jitsiwebrtc

**Comment by mawburn** [comment]
@CaosFR awesome, ty. I was going to try out a camera module myself anyway so I'll take a look!

**Comment by CaosFR** [comment]
Thanks :)

**Comment by CaosFR** [comment]
Update : I'm now using https://github.com/bekriebel/fvtt-module-avclient-livekit

**Comment by mawburn** [comment]
Yeah, I think ultimately this is something that those developers need to keep up with. I looked into it last time and I can't really do a whole lot.

But thanks for pointing me at a new video client! I was sad when jitsi was deprecated.
