### ISSUE TITLE
Ping times disappear when a user connects or disconnects

### ISSUE THREAD

**Issue by cs96and** [mawburn/foundry-user-latency#5]
If a user connects to or disconnects from the game, all ping times disappear.  You have to wait for the next ping to happen for them to re-appear.

**Comment by mawburn** [comment]
I noticed this the other day, I'll see if I can put in a fix for it. I think it's related to the new way v9 is doing IDs or I just didn't notice it before.

**Comment by cs96and** [comment]
Happens in 0.8 too.  I haven't upgraded to v9 yet
