### ISSUE TITLE
Error when trying to install and download 1.29.19 pointing to 1.2.20

### ISSUE THREAD

**Issue by kcits** [mawburn/foundry-user-latency#6]
I get the following in console
Error: An unexpected error occurred when downloading file https://github.com/mawburn/foundry-ping-logger/releases/download/v1.2.20/module.zip: Not Found

Checked other install which has it at 1.2.18 and gives same error

**Comment by mawburn** [comment]
Whoops. Good catch. Thanks for reporting. I'll fix this tonight.

**Comment by mawburn** [comment]
Should be good, sorry about that.
