### ISSUE TITLE
Ping Logger vs. User Latency

### ISSUE THREAD

**Issue by Weissrolf** [mawburn/foundry-user-latency#7]
Hello.

For some reason my list of modules includes two versions of the module going by different names now. I prefer the "Ping Logger" variant, because "User Latency" does not make full use of the user list window width and cuts off part of the content.

User Latency:
![](https://i.imgur.com/cNAzTLe.png)

Ping Logger:
![](https://i.imgur.com/VS998Da.png)

**Comment by mawburn** [comment]
It was just a name change, nothing else changed.

**Comment by mawburn** [comment]
This could be caused by other plugins you may have installed, but this change specifically wouldn't have caused this.

Here is a comparison. It's just a name change. 

https://github.com/mawburn/foundry-user-latency/compare/v1.2.20...v1.2.21

**Comment by mawburn** [comment]
ACTUALLY, you're right. My bad. 

https://github.com/mawburn/foundry-user-latency/compare/v1.2.20...v1.2.21#diff-a266dd3ec05ed7ee480ce06330f73682ba8be8c3b45a6c4582b088db7502a153R12-R13

The capitalization broke it. I'm not sure why it didn't break on my end. Good catch.

**Comment by Weissrolf** [comment]
Thanks for the quick fix! 👍

**Comment by mawburn** [comment]
No problem! Let me know if you have more issues. Sorry I dismissed this at first.

**Comment by Weissrolf** [comment]
Unfortunately the latest .23 still did not fix it.

![](https://i.imgur.com/u3aZEIY.png)

**Comment by Weissrolf** [comment]
I disabled all modules for the last screenshot. PF2 system. Foundry v10.286

**Comment by mawburn** [comment]
Yeah, I broke stuff last night trying to rush some other changes. My bad. Sorry about that. Will fix before work.

**Comment by mawburn** [comment]
Done. Fixed. Finished. I hope. lol

Sorry about that, I was rushing before leaving the house yesterday. I shouldn't have done that. But now it has some new features!
