### ISSUE TITLE
Contrast detection failing

### ISSUE THREAD

**Issue by lektu** [mawburn/foundry-user-latency#8]
From the same Windows, and the same Chrome instance, with setup
- Hide latency completely [ ]
- Show only dots instead of numbers [X]

Accessing to my local instance (Electron, on Windows, Foundry version 10.286), it works as expected: I see a right aligned "+" inside a green dot.

Accessing to my remote instance (The Forge, Foundry version 9.280), I see a left-aligned "+" with no dot, or just nothing (I imagine that's the "neutral status", without color).

Don't know if the differences are caused by V9 vs V10, or local vs. The Forge.

![image](https://user-images.githubusercontent.com/833999/193086509-d1ce4515-a540-43a9-ae8b-5a664bc7f9b0.png)
![image](https://user-images.githubusercontent.com/833999/193086549-75980fb5-ddb7-4ca4-afbd-86cbfd5efb3b.png)

**Comment by mawburn** [comment]
You might have the setting `prefers low contrast` enabled somewhere in Windows. 

Specifically it's looking for low contrast only. But if already causing issues like this I'll just remove that embedded option. People who have issues with it can just hide it. 

https://support.microsoft.com/en-us/windows/change-color-contrast-in-windows-fedc744c-90ac-69df-aed5-c8a90125e696#:~:text=Select%20the%20Start%20button%2C%20and%20then%20select%20Settings%20%3E%20Ease%20of,colors%20on%20the%20screen%20change

**Comment by mawburn** [comment]
However, make sure the module is up to date. I had a lot of pushes today because of stupidness on my end.

**Comment by lektu** [comment]
For some reason, The Forge hadn't yet updated the module. It's now at 1.3.8 and working as expected. Sorry for the noise.

**Comment by lektu** [comment]
A weird thing, though, is that expanding/collapsing the player list does not keep the existing latency marker (they don't appear until the next refresh). Perhaps it'd be best to trigger an update when the player list's status changes.

**Comment by mawburn** [comment]
> For some reason, The Forge hadn't yet updated the module. It's now at 1.3.8 and working as expected. Sorry for the noise.

Oh cool! No worries. 

> A weird thing, though, is that expanding/collapsing the player list does not keep the existing latency marker (they don't appear until the next refresh). Perhaps it'd be best to trigger an update when the player list's status changes.

Yeah, I could probably listen for something like that. I honestly didn't do a whole lot to the core functionality when I took it over other than fix the underlying ping mechanism and convert it to a better language. I am starting to add a little bit after my reddit thread.
